apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 4
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: alvin254/fitnesshero:v1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: gym-app-service
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort